# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required

site_name: Manual DICOM y NIFTI
site_description: Manuales de auyda en procesamiento de Neuroimágenes
repo_url: https://github.com/pabloreyesg/Scrips-to-MRI
site_url: https://github.com/pabloreyesg/Scrips-to-MRI/blob/master/docs/index.md
site_author: Pablo Reyes
copyright: Copyright &copy; 2021 Pablo Reyes

theme: readthedocs

nav:
    - Anonimizacion: index.md
    - Conversion NIFTI : dcm2nii.md
    - Conversion BIDS: BIDScon.md
    - About: about.md
    - Primeros Pasos: Firststeps.md


extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<pabloreyesg@gmail.com>
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/parapapush
